sudo: false
language: ruby
rvm:
  - 2.6.1

env:
  - RUBY_VERSION_FOR_DEPLOY=2.6.2
branches:
  only:
    - master
cache: bundler
before_install:
  - travis_retry gem update --system
  - travis_retry gem install bundler
  - bundle install
install:
  - travis_retry bundle install --jobs=3 --retry=3
  - bundle exec jekyll build

